/* Insertando roles por defecto */
INSERT INTO ROLES (ID, NOMBRE) VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLES (ID, NOMBRE) VALUES (2, 'ROLE_USUARIO');
/* Insertando usuario por defecto */
INSERT INTO USUARIOS (NOMBRE, APELLIDOS, FECHA_NACIMIENTO, DIRECCION, EMAIL, CLAVE, ROLE, ESTADO) VALUES ('Juan', 'Arboleda', NOW(), '', 'asd@asd.asd', '$2a$10$ibYGGYyyd3W0rE/.QVU9TeviVc5oJUlkr2cAE8WHRTji2/9YwNl7i', 1, 1);
INSERT INTO USUARIOS (NOMBRE, APELLIDOS, FECHA_NACIMIENTO, DIRECCION, EMAIL, CLAVE, ROLE, ESTADO) VALUES ('Pepito', 'Perez', NOW(), '', 'inactive@asd.asd', '$2a$10$ibYGGYyyd3W0rE/.QVU9TeviVc5oJUlkr2cAE8WHRTji2/9YwNl7i', 2, 0);
